spring:
  application:
    name: springboot-rest-api-service

  main:
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:mysql://localhost:3306/multidatahub
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  liquibase:
    change-log: classpath:db/changelog/changelog.yaml
    enabled: true

  jpa:
    show-sql: false
    open-in-view: false

  task:
    scheduling:
      pool:
        size: 10

server:
  port: 8888

jwt:
  secret: EPDE
