spring:
  application:
    name: springboot-rest-api-service

  datasource:
    url: jdbc:mysql://localhost:3306/multidatahub
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  liquibase:
    change-log: classpath:db/changelog/changelog.yaml

  jpa:
    show-sql: false
    open-in-view: false

server:
  port: 8888

jwt:
  secret: EPDE

