spring:
  application:
    name: springboot-rest-api-service

  profiles:
    active: mosfik

  main:
    allow-bean-definition-overriding: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  liquibase:
    change-log: classpath:db/changelog/changelog.yaml
    enabled: true

  jpa:
    show-sql: false
    open-in-view: false

  task:
    scheduling:
      pool:
        size: 10

server:
  port: 8888
  servlet:
    context-path: /api/v1

logging:
  pattern:
    console: "%d{yyyy-MM-dd hh:mm:ss a} | %highlight(%level) | [%file:%line] - %msg%n"
